### ISSUE TITLE
The log file gets deleted

### ISSUE THREAD

**Issue by egemen-cimen** [WikiBox/snapshot.sh#1]
The log file `rsync.log` doesn't appear in `"$destination"/unfinished/` directory after rsync operation This may be a result of the `--delete` option to rsync:
<pre>
rsync -a --delete --stats \
      --link-dest="$destination"/"$latest_snapshot" \
      "$source" \
      "$destination"/unfinished > "$destination"/unfinished/rsync.log 
</pre>
Removing the `--delete` option appears to solve this problem and I believe it can be removed without changing the behavior of the script.

**Comment by jdawgzim** [comment]
Yes, is **--delete** even needed since **--link-dest** is basically creating snapshots by not copying things that already exist in previous snapshots?  

Since this is always creating a new snapshot it would never have anything to actually delete in the destination.  Right?

EDIT: I guess it depends on the behavior of **--link-dest**.  Does --link-dest link to all files or only to files it finds from the source?

**Comment by WikiBox** [comment]
The log file is not deleted. It is written to $destination/unfinished but provided the rsync command finish without error, that folder will be renamed to $destination/$snapshot_name. And the log file will be inside that folder.

--delete is needed: The rsync command may fail for some reason. A partial .unfinished snapshot will remain. This is a nice feature for big snapshots, since the script can "resume" a snapshot using the existing .unfinished snapshot. It is possible that files have been deleted in the source between the rsync command failed and the script was run again. Those files need to be deleted in .unfinished to produce a correct snapshot.
